### ISSUE TITLE
Head "https://gchr.io/v2/userver-framework/..." denied: denied

### ISSUE THREAD

**Issue by eoan-ermine** [userver-framework/pg_service_template#9] opened 2022-07-31 16:16 UTC
1. git clone git@github.com:userver-framework/pg_service_template.git
2. cd pg_service_template/
3. make docker-test-debug

Output:
```
docker-compose run --rm pg_service_template-service make test-debug
Creating network "pg_service_template_postgres" with driver "bridge"
Pulling pg_service_template-service (ghcr.io/userver-framework/docker-userver-build-base:v1)...
ERROR: Head "https://ghcr.io/v2/userver-framework/docker-userver-build-base/manifests/v1": denied: denied
make: *** [Makefile:86: docker-impl-test-debug] Error 1
```

**Comment by alexiprof** [comment] 2022-08-02 11:34
Hi, thanks for contacting us. Please write on which operating system are you trying to run docker and under which architecture?

**Comment by alexiprof** [comment] 2023-03-07 09:00
There is no answer to the question for a long time, after the question several changes were made to the package visibility, now everything should be available. I'm closing the issue, if the problem is relevant, create a new one.

**Closed as not planned by alexiprof** 2023-03-07 09:00 UTC
